Ds 3268
Displayr/flipChart pull request #17
Opened 2021-04-01 02:40 UTC by chschan

2021-04-01 05:31 UTC, jrwishart requested changes

2021-04-01 05:31 UTC, jrwishart commented on R/cchart.R
> +        chart.labels$PrimaryAxisTitle <- categories.title
This looks to be a typo and the second `if` statement above should be checking if `categories.title` has any characters

2021-04-01 05:31 UTC, jrwishart commented on R/cchart.R
> +    if (isTRUE(args$legend.show == FALSE) || isTRUE(args$legend.show == "Hide") || tmp.n == 1)
can replace the first `isTRUE` with `isFALSE`

2021-04-06 00:40 UTC, chschan commented on R/cchart.R
> +        chart.labels$PrimaryAxisTitle <- categories.title
Thanks for picking that up! I've fixed this now and modified one of the tests so it would pick up this problem.

2021-04-06 00:41 UTC, chschan commented on R/cchart.R
> +    if (isTRUE(args$legend.show == FALSE) || isTRUE(args$legend.show == "Hide") || tmp.n == 1)
I don't think it replaceable because `isFALSE(NULL)` is FALSE

2021-04-06 04:25 UTC, jrwishart commented on R/cchart.R
> +    if (isTRUE(args$legend.show == FALSE) || isTRUE(args$legend.show == "Hide") || tmp.n == 1)
`isTRUE(NULL)` is also `FALSE` though.

2021-04-06 06:55 UTC, chschan commented on R/cchart.R
> +    if (isTRUE(args$legend.show == FALSE) || isTRUE(args$legend.show == "Hide") || tmp.n == 1)
Ok, using isFALSE in 15424b6

2021-04-07 03:01 UTC, jrwishart approved these changes

2021-04-07 03:04 UTC, merged